version: 2.1

orbs:
  scala-build: liveintent/scala-build@10.0
  node: circleci/node@5.1

parameters:
  node_version:
    type: string
    # This should match with the cimg/node version
    default: "18.18.0"

executors:
  machine_runner:
    machine:
      image: ubuntu-2204:2023.10.1
  browserstack_runner:
    docker:
      - image: cimg/node:18.18
    resource_class: liveintent/browserstack
  node_runner:
    docker:
      - image: cimg/node:18.18

references:
  releasable_branch: &releasable_branch
    branches:
      only: master
    tags:
      only: /^$/

  manual_branch: &manual_branch
    branches:
      ignore: /dependabot\/.*/
    tags:
      only: /^$/

  update_pr: &update_pr
    branches:
      only: /dependabot\/.*/
    tags:
      only: /^$/

  untagged_commit: &untagged_commit
    tags:
      only: /^$/

  restore_cache: &restore_cache
    restore_cache:
      key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}

  save_cache: &save_cache
    save_cache:
      key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      paths:
        - ./node_modules

  npm_install: &npm_install
    run:
      name: Install dependencies
      command: |
        npm install
        npm install --no-save @rollup/rollup-linux-x64-gnu

  host_setup: &host_setup
    run:
      name: Setup host entries for TLD tests
      command: |
        echo "127.0.0.1 bln.test.liveintent.com" | sudo tee -a /etc/hosts
        echo "127.0.0.1 test.liveintent.com" | sudo tee -a /etc/hosts
        echo "127.0.0.1 me.idex.com" | sudo tee -a /etc/hosts
        echo "127.0.0.1 schmoogle.com" | sudo tee -a /etc/hosts
        echo "127.0.0.1 framed.test.liveintent.com" | sudo tee -a /etc/hosts
        echo "127.0.0.1 double-framed.test.liveintent.com" | sudo tee -a /etc/hosts
        echo "127.0.0.1 baked.liveintent.com" | sudo tee -a /etc/hosts

  configure_git: &configure_git
    run:
      name: Configure Git
      command: |
        git config user.name "${CIRCLE_USERNAME}"
        git config user.email "dev-berlin@liveintent.com"
        git branch -u origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}

  set_ssh_key: &set_ssh_key
    add_ssh_keys:
      fingerprints:
        - "7a:01:2b:33:51:54:c5:3d:d5:e6:da:12:14:09:53:b7"

  reset_package_lock: &reset_package_lock
    run:
      name: Reset package-lock.json
      command: git checkout -- package-lock.json

jobs:
  simple_test:
    executor: machine_runner
    steps:
      - checkout
      - *restore_cache
      - *host_setup
      - node/install:
          node-version:  << pipeline.parameters.node_version >>
      - *npm_install
      - *save_cache
      - run:
          name: Run unit tests
          command: npm run test:unit
      - run:
          name: Run chrome tests
          command: npm run test:it:local-chrome
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: ./test-results
          destination: test-results
      - run:
          name: Code Coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN}

  browserstack:
    executor: browserstack_runner
    steps:
      - checkout
      - *restore_cache
      - *host_setup
      - *npm_install
      - run:
          name: Run browserstack tests
          command: npm run test:it:browserstack
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: ./test-results
          destination: test-results

  release:
    executor: node_runner
    parameters:
      increment:
        description: |
          "Increment of release. Allowed values `prepatch`, `preminor`, `premajor`,
          `alpha->beta`, `beta->rc`, `patch`, `minor`, `major`"
        default: "patch"
        type: string
    steps:
      - checkout
      - *npm_install
      - *configure_git
      - *set_ssh_key
      - *reset_package_lock
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: release
          command: npm run release:ci:<< parameters.increment >>

workflows:
  version: 2
  build_and_test:
    jobs:
      - simple_test:
          filters:
            <<: *untagged_commit

      - browserstack?:
          type: approval
          requires:
            - simple_test
          filters:
            <<: *manual_branch

      - browserstack:
          name: browserstack_manual
          context:
            - org-global
          requires:
            - browserstack?

      - browserstack:
          name: browserstack_update_pr
          context:
            - org-global
          requires:
            - simple_test
          filters:
            <<: *update_pr

      - scala-build/merge_pr:
          context: org-global
          requires:
            - browserstack_update_pr
          filters:
            <<: *update_pr

      - release_prepatch?:
          context: live-connect
          type: approval
          requires:
            - browserstack_manual
          filters:
            <<: *manual_branch

      - release:
          context: live-connect
          name: release_prepatch
          increment: "prepatch"
          requires:
            - release_prepatch?

      - release_preminor?:
          context: live-connect
          type: approval
          requires:
            - browserstack_manual
          filters:
            <<: *manual_branch

      - release:
          context: live-connect
          name: release_preminor
          increment: "preminor"
          requires:
            - release_preminor?

      - release_premajor?:
          context: live-connect
          type: approval
          requires:
            - browserstack_manual
          filters:
            <<: *manual_branch

      - release_bump_prerelease?:
          context: live-connect
          type: approval
          requires:
            - browserstack_manual
          filters:
            <<: *manual_branch

      - release:
          context: live-connect
          name: release_bump_prerelease
          increment: "bump-prerelease"
          requires:
            - release_bump_prerelease?

      - release:
          context: live-connect
          name: release_premajor
          increment: "premajor"
          requires:
            - release_premajor?

      - release_alpha->beta?:
          context: live-connect
          type: approval
          requires:
            - browserstack_manual
          filters:
            <<: *releasable_branch

      - release:
          context: live-connect
          name: release_alpha->beta
          increment: "alpha->beta"
          requires:
            - release_alpha->beta?

      - release_beta->rc?:
          context: live-connect
          type: approval
          requires:
            - browserstack_manual
          filters:
            <<: *releasable_branch

      - release:
          context: live-connect
          name: release_beta->rc
          increment: "beta->rc"
          requires:
            - release_beta->rc?

      - release_patch?:
          context: live-connect
          type: approval
          requires:
            - browserstack_manual
          filters:
            <<: *releasable_branch

      - release:
          context: live-connect
          name: release_patch
          increment: "patch"
          requires:
            - release_patch?

      - release_minor?:
          context: live-connect
          type: approval
          requires:
            - browserstack_manual
          filters:
            <<: *releasable_branch

      - release:
          context: live-connect
          name: release_minor
          increment: "minor"
          requires:
            - release_minor?

      - release_major?:
          context: live-connect
          type: approval
          requires:
            - browserstack_manual
          filters:
            <<: *releasable_branch

      - release:
          context: live-connect
          name: release_major
          increment: "major"
          requires:
            - release_major?

  daily-master:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master
    jobs:
      - simple_test

      - browserstack:
          requires:
            - simple_test
          context:
            - org-global
